#! /bin/sh

# Kill previous hotkey daemon instances
pkill sxhkd

# Faster keyboard
xset r rate 300 50

# Swap caps with escape
setxkbmap -option caps:swapescape

# Key daemon
pgrep -x sxhkd > /dev/null || sxhkd &

# Compositor (picom-ibhagwan)
picom --experimental-backends &

# Wallpaper and colorscheme
wal -R

# Monitors
bspc monitor -d I II III IV V VI VII VIII IX X

# bspwm borders and gaps
bspc config border_width         5
bspc config window_gap          10

# Ratio and other
bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false

# bspwm rules
bspc rule -a Gimp state=floating follow=on
bspc rule -a mpv state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a MultiMC state=floating

# Toggle between Russian and English layouts
setxkbmap -option grp:alt_shift_toggle us,ru

# xscreensaver
xscreensaver -no-splash &
# polybar
~/.config/polybar/start.sh
# mate-polkit
/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"
